
name: Destroy OpenFaaS Environment

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - working-directory: ./terraform
        run: terraform init

      - working-directory: ./terraform
        env:
          TF_VAR_openfaas_uri: ${{ secrets.OPENFAAS_URL }}
          TF_VAR_openfaas_user: admin
          TF_VAR_openfaas_password: ${{ secrets.OPENFAAS_PASSWORD }}
          TF_VAR_image_tag: "latest"
        run: terraform destroy -auto-approve