name: OpenFaaS Auto-Deploy

on:
  push:
    branches:
      - main
      - master # Included just in case your default branch is named master

env:
  IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/hello-node:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        run: |
          # Replace the dummy image name with your tagged image
          sed -i "s|image:.*|image: ${{ env.IMAGE_TAG }}|g" stack.yaml
          faas-cli build -f stack.yaml
          faas-cli push -f stack.yaml

  terraform-deploy:
    needs: [build-and-push]
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_VAR_openfaas_uri: ${{ secrets.OPENFAAS_URL }}
          TF_VAR_openfaas_user: ${{ secrets.OPENFAAS_USER }}
          TF_VAR_openfaas_password: ${{ secrets.OPENFAAS_PASSWORD }}
          TF_VAR_image_tag: ${{ env.IMAGE_TAG }}
        run: terraform apply -auto-approve